// Generated by CoffeeScript 1.10.0
(function() {
  exports.config = {
    host: "192.168.13.1",
    port: '3306',
    user: 'root',
    password: 'sunsasi',
    database: 'mzdb'
  };

}).call(this);
