// Generated by CoffeeScript 1.10.0
(function() {
  var a, cheerio, http, i, item, request, spider;

  request = require('superagent');

  cheerio = require('cheerio');

  http = require('http');

  a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11];

  spider = function(url) {
    return request.get(url).end(function(err, res) {
      var $;
      if (!err) {
        $ = cheerio.load(res.text);
        return $('#list_article .single_fake div div a').each(function() {
          console.log(url);
          console.log("   title:" + $(this).attr('title'));
          console.log("   href:" + $(this).attr('href'));
          console.log("   text:" + $(this).text());
          return console.log("=======================================1====");
        });
      } else {
        return console.log('err');
      }
    });
  };

  for (item = i = 0; i <= 30; item = ++i) {
    spider('http://www.tuicool.com/ah/0/' + item.toString() + '?lang=1');
  }

}).call(this);

//# sourceMappingURL=index.js.map
